-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

SET search_path = app_basic_demo,public;

CREATE OR REPLACE FUNCTION ora2pg_upd_autoincrement_seq (tbname text, colname text) RETURNS VOID AS $body$
DECLARE
        query text;
        maxval bigint;
        seqname text;
BEGIN
        query := 'SELECT max(' || colname || ')+1 FROM ' || tbname || '';
        EXECUTE query INTO maxval;
        IF (maxval IS NOT NULL) THEN
		query := $$SELECT pg_get_serial_sequence ('$$|| tbname || $$', '$$ || colname || $$');$$;
                EXECUTE query INTO seqname;
                IF (seqname IS NOT NULL) THEN
                        query := 'ALTER SEQUENCE ' || seqname || ' RESTART WITH ' || maxval;
                        EXECUTE query;
                END IF;
        ELSE
                RAISE NOTICE 'Table % is empty, you must load the AUTOINCREMENT file after data import.', tbname;
        END IF;
END;
$body$
LANGUAGE PLPGSQL;

SELECT ora2pg_upd_autoincrement_seq('bestellungen','id');
SELECT ora2pg_upd_autoincrement_seq('produkte','id');
DROP FUNCTION ora2pg_upd_autoincrement_seq(text, text);
