-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

SET search_path = app_basic_demo,public;


CREATE TABLE bestellungen (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	produkt_id bigint NOT NULL,
	menge bigint NOT NULL,
	bestelldatum timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	aktualisiert_am timestamp(0)
) ;
ALTER TABLE bestellungen ADD PRIMARY KEY (id);
ALTER TABLE bestellungen ALTER COLUMN ID SET NOT NULL;
ALTER TABLE bestellungen ALTER COLUMN PRODUKT_ID SET NOT NULL;
ALTER TABLE bestellungen ALTER COLUMN MENGE SET NOT NULL;
ALTER TABLE bestellungen ALTER COLUMN BESTELLDATUM SET NOT NULL;


CREATE TABLE produkte (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	name varchar(100) NOT NULL,
	beschreibung varchar(500),
	preis decimal(10,2) NOT NULL,
	lagerbestand bigint NOT NULL DEFAULT 0,
	erstellt_am timestamp(0) NOT NULL DEFAULT statement_timestamp()
) ;
ALTER TABLE produkte ADD PRIMARY KEY (id);
ALTER TABLE produkte ALTER COLUMN ID SET NOT NULL;
ALTER TABLE produkte ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE produkte ALTER COLUMN PREIS SET NOT NULL;
ALTER TABLE produkte ALTER COLUMN LAGERBESTAND SET NOT NULL;
ALTER TABLE produkte ALTER COLUMN ERSTELLT_AM SET NOT NULL;
ALTER TABLE bestellungen ADD CONSTRAINT fk_best_produkt FOREIGN KEY (produkt_id) REFERENCES produkte(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
