-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

SET search_path = app_basic_demo,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS trg_bestellung_update ON bestellungen CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg_bestellung_update() RETURNS trigger AS $BODY$
BEGIN
  NEW.AKTUALISIERT_AM := statement_timestamp();
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_trg_bestellung_update() FROM PUBLIC;

CREATE TRIGGER trg_bestellung_update
	BEFORE UPDATE ON bestellungen FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_trg_bestellung_update();

