-- Testdaten fuer APP_BASIC_DEMO

ALTER SESSION SET CONTAINER = XEPDB1;

INSERT INTO APP_BASIC_DEMO.PRODUKTE (NAME, BESCHREIBUNG, PREIS, LAGERBESTAND)
  VALUES ('Laptop Pro 15', 'Business-Laptop mit 15-Zoll-Display, Intel Core i7', 1299.99, 25);
INSERT INTO APP_BASIC_DEMO.PRODUKTE (NAME, BESCHREIBUNG, PREIS, LAGERBESTAND)
  VALUES ('USB-C Maus', 'Ergonomische kabellose Maus, 2.4 GHz', 49.99, 150);
INSERT INTO APP_BASIC_DEMO.PRODUKTE (NAME, BESCHREIBUNG, PREIS, LAGERBESTAND)
  VALUES ('Mechanische Tastatur', 'TKL-Layout, Cherry MX Brown, DE-Layout', 129.00, 80);
INSERT INTO APP_BASIC_DEMO.PRODUKTE (NAME, BESCHREIBUNG, PREIS, LAGERBESTAND)
  VALUES ('Monitor 27 4K', '27 Zoll IPS, 4K UHD, USB-C 65W PD', 649.00, 40);
INSERT INTO APP_BASIC_DEMO.PRODUKTE (NAME, BESCHREIBUNG, PREIS, LAGERBESTAND)
  VALUES ('USB-C Hub 7-Port', 'HDMI 4K + 3x USB-A + SD/microSD + PD 100W', 79.90, 200);

INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (1, 2, DATE '2024-01-15');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (2, 5, DATE '2024-01-20');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (3, 3, DATE '2024-02-01');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (1, 1, DATE '2024-02-10');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (4, 4, DATE '2024-02-14');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (5, 10, DATE '2024-03-05');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (2, 8, DATE '2024-03-12');
INSERT INTO APP_BASIC_DEMO.BESTELLUNGEN (PRODUKT_ID, MENGE, BESTELLDATUM)
  VALUES (3, 2, DATE '2024-03-20');

COMMIT;

EXIT;
