-- =============================================================
-- 02_schema.sql
-- Tabellen, Constraints, Indizes im Schema APP_DEMO.
-- =============================================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APP_DEMO;

-- ---------- KUNDEN ----------
CREATE TABLE kunden (
    id           NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anrede       VARCHAR2(10),
    vorname      VARCHAR2(50)  NOT NULL,
    name         VARCHAR2(50)  NOT NULL,
    email        VARCHAR2(100) NOT NULL,
    telefon      VARCHAR2(30),
    strasse      VARCHAR2(100),
    plz          VARCHAR2(10),
    ort          VARCHAR2(60),
    land         VARCHAR2(2)   DEFAULT 'DE' NOT NULL,
    erstellt_am  DATE          DEFAULT SYSDATE NOT NULL,
    aktiv        NUMBER(1)     DEFAULT 1       NOT NULL,
    CONSTRAINT uk_kunden_email UNIQUE (email),
    CONSTRAINT ck_kunden_aktiv CHECK (aktiv IN (0, 1))
);

COMMENT ON TABLE  kunden              IS 'Stammdaten Kunden';
COMMENT ON COLUMN kunden.aktiv        IS '0=inaktiv, 1=aktiv';
COMMENT ON COLUMN kunden.land         IS 'ISO-3166 alpha-2';

-- Funktionaler Index fuer case-insensitive E-Mail-Suche
CREATE INDEX idx_kunden_email_upper ON kunden(UPPER(email));

-- ---------- RECHNUNGEN ----------
CREATE TABLE rechnungen (
    id               NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rechnungsnummer  VARCHAR2(20)  NOT NULL,
    kunden_id        NUMBER        NOT NULL,
    rechnungsdatum   DATE          DEFAULT SYSDATE NOT NULL,
    faellig_am       DATE,
    betrag_netto     NUMBER(10,2)  NOT NULL,
    mwst_satz        NUMBER(4,2)   DEFAULT 19.00 NOT NULL,
    betrag_brutto    NUMBER(10,2)  NOT NULL,
    status           VARCHAR2(20)  DEFAULT 'OFFEN' NOT NULL,
    bemerkung        CLOB,
    geaendert_am     TIMESTAMP,
    CONSTRAINT uk_rechnungsnummer  UNIQUE (rechnungsnummer),
    CONSTRAINT fk_rechnung_kunde   FOREIGN KEY (kunden_id) REFERENCES kunden(id),
    CONSTRAINT ck_rechnung_status  CHECK (status IN ('OFFEN','BEZAHLT','STORNIERT','MAHNUNG')),
    CONSTRAINT ck_rechnung_betrag  CHECK (betrag_netto >= 0 AND betrag_brutto >= 0)
);

-- Composite-Index auf (kunden_id, rechnungsdatum DESC) deckt auch den
-- einfachen Lookup nach kunden_id ab (leftmost prefix).
CREATE INDEX idx_rechnungen_kunde_datum ON rechnungen(kunden_id, rechnungsdatum DESC);
CREATE INDEX idx_rechnungen_status      ON rechnungen(status);

COMMENT ON TABLE  rechnungen              IS 'Rechnungskopf, je Kunde beliebig viele';
COMMENT ON COLUMN rechnungen.geaendert_am IS 'Letzte Aenderung via trg_rechnungen_aud gesetzt';

-- ---------- RECHNUNGSPOSITIONEN ----------
CREATE TABLE rechnungspositionen (
    id             NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rechnung_id    NUMBER        NOT NULL,
    position       NUMBER        NOT NULL,
    beschreibung   VARCHAR2(200) NOT NULL,
    menge          NUMBER(10,3)  DEFAULT 1  NOT NULL,
    einheit        VARCHAR2(20)  DEFAULT 'Stk' NOT NULL,
    einzelpreis    NUMBER(10,2)  NOT NULL,
    gesamtpreis    NUMBER(10,2)  NOT NULL,
    position_summe NUMBER(12,2),
    CONSTRAINT fk_pos_rechnung FOREIGN KEY (rechnung_id) REFERENCES rechnungen(id) ON DELETE CASCADE,
    CONSTRAINT uk_pos_rechnung UNIQUE (rechnung_id, position),
    CONSTRAINT ck_pos_menge    CHECK (menge > 0),
    CONSTRAINT ck_pos_preis    CHECK (einzelpreis >= 0 AND gesamtpreis >= 0)
);

CREATE INDEX ix_pos_rechnung ON rechnungspositionen(rechnung_id);

COMMENT ON TABLE  rechnungspositionen                IS 'Einzelne Positionen einer Rechnung';
COMMENT ON COLUMN rechnungspositionen.position_summe IS 'menge * einzelpreis, via trg_position_summe gesetzt';

EXIT;
