-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

SET search_path = app_demo,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;



-- Oracle package 'PKG_FAKTURA' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS pkg_faktura CASCADE;
CREATE SCHEMA IF NOT EXISTS pkg_faktura;



--------------------------------------------------------------
CREATE OR REPLACE FUNCTION pkg_faktura.get_kunde (p_id bigint) RETURNS KUNDEN AS $body$
DECLARE

        v_row kunden%ROWTYPE;

BEGIN
        RAISE NOTICE 'pkg_faktura.get_kunde(%)', p_id;
        SELECT *
          INTO STRICT v_row
          FROM kunden
         WHERE id = p_id;
        RETURN v_row;
    EXCEPTION
        WHEN no_data_found THEN
            RAISE NOTICE '  -> Kunde nicht gefunden';
            RAISE EXCEPTION 'e_kunde_nicht_gefunden' USING ERRCODE = '50001';
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pkg_faktura.get_kunde (p_id bigint) FROM PUBLIC;

    --------------------------------------------------------------
CREATE OR REPLACE FUNCTION pkg_faktura.kunde_umsatz (p_kunde_id bigint) RETURNS bigint AS $body$
DECLARE

        v_summe bigint;

BEGIN
        RAISE NOTICE 'pkg_faktura.kunde_umsatz(%)', p_kunde_id;
        SELECT coalesce(SUM(betrag_brutto), 0)
          INTO STRICT v_summe
          FROM rechnungen
         WHERE kunden_id = p_kunde_id
           AND status    = 'BEZAHLT';
        RETURN v_summe;
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pkg_faktura.kunde_umsatz (p_kunde_id bigint) FROM PUBLIC;

    --------------------------------------------------------------
CREATE OR REPLACE FUNCTION pkg_faktura.berechne_rechnungssumme (p_rechnung_id bigint) RETURNS bigint AS $body$
DECLARE

        v_summe bigint;

BEGIN
        RAISE NOTICE 'pkg_faktura.berechne_rechnungssumme(%)', p_rechnung_id;
        SELECT coalesce(SUM(position_summe), 0)
          INTO STRICT v_summe
          FROM rechnungspositionen
         WHERE rechnung_id = p_rechnung_id;
        RETURN v_summe;
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pkg_faktura.berechne_rechnungssumme (p_rechnung_id bigint) FROM PUBLIC;

    --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE pkg_faktura.erstelle_kunde (p_vorname text, p_name text, p_email text, p_id INOUT bigint) AS $body$
BEGIN
        RAISE NOTICE 'pkg_faktura.erstelle_kunde(%)', p_email;
        INSERT INTO kunden(vorname, name, email)
             VALUES (p_vorname, p_name, p_email)
          RETURNING id INTO p_id;
        RAISE NOTICE '  -> neue Kunden-ID = %', p_id;
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE pkg_faktura.erstelle_kunde (p_vorname text, p_name text, p_email text, p_id INOUT bigint) FROM PUBLIC;

    --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE pkg_faktura.setze_rechnungs_status (p_rechnung_id bigint, p_status text) AS $body$
DECLARE

        v_count bigint;

BEGIN
        RAISE NOTICE 'pkg_faktura.setze_rechnungs_status(%, %)', p_rechnung_id, p_status;

        IF p_status NOT IN ('OFFEN','BEZAHLT','MAHNUNG','STORNIERT') THEN
            RAISE NOTICE '  -> ungueltiger Status';
            RAISE EXCEPTION 'e_ungueltiger_status' USING ERRCODE = '50003';
        END IF;

        UPDATE rechnungen
           SET status = p_status
         WHERE id = p_rechnung_id;

        GET DIAGNOSTICS v_count = ROW_COUNT;
        IF v_count = 0 THEN
            RAISE NOTICE '  -> Rechnung nicht gefunden';
            RAISE EXCEPTION 'e_rechnung_nicht_gefunden' USING ERRCODE = '50002';
        END IF;

        RAISE NOTICE '  -> % Zeile(n) aktualisiert', v_count;
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE pkg_faktura.setze_rechnungs_status (p_rechnung_id bigint, p_status text) FROM PUBLIC;
-- End of Oracle package 'PKG_FAKTURA' declaration

