-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

SET search_path = app_demo,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;

-- Nothing found of type SEQUENCE
