-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

SET search_path = app_demo,public;


CREATE TABLE kunden (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	anrede varchar(10),
	vorname varchar(50) NOT NULL,
	name varchar(50) NOT NULL,
	email varchar(100) NOT NULL,
	telefon varchar(30),
	strasse varchar(100),
	plz varchar(10),
	ort varchar(60),
	land varchar(2) NOT NULL DEFAULT 'DE',
	erstellt_am timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	aktiv smallint NOT NULL DEFAULT 1
) ;
COMMENT ON TABLE kunden IS E'Stammdaten Kunden';
COMMENT ON COLUMN kunden.aktiv IS E'0=inaktiv, 1=aktiv';
COMMENT ON COLUMN kunden.land IS E'ISO-3166 alpha-2';
CREATE INDEX idx_kunden_email_upper ON kunden (upper(email));
ALTER TABLE kunden ADD UNIQUE (email);
ALTER TABLE kunden ADD PRIMARY KEY (id);
ALTER TABLE kunden ADD CONSTRAINT ck_kunden_aktiv CHECK (aktiv IN (0, 1));
ALTER TABLE kunden ALTER COLUMN ID SET NOT NULL;
ALTER TABLE kunden ALTER COLUMN VORNAME SET NOT NULL;
ALTER TABLE kunden ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE kunden ALTER COLUMN EMAIL SET NOT NULL;
ALTER TABLE kunden ALTER COLUMN LAND SET NOT NULL;
ALTER TABLE kunden ALTER COLUMN ERSTELLT_AM SET NOT NULL;
ALTER TABLE kunden ALTER COLUMN AKTIV SET NOT NULL;


CREATE TABLE rechnungen (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	rechnungsnummer varchar(20) NOT NULL,
	kunden_id bigint NOT NULL,
	rechnungsdatum timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	faellig_am timestamp(0),
	betrag_netto decimal(10,2) NOT NULL,
	mwst_satz decimal(4,2) NOT NULL DEFAULT 19.00,
	betrag_brutto decimal(10,2) NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'OFFEN',
	bemerkung text,
	geaendert_am timestamp
) ;
COMMENT ON TABLE rechnungen IS E'Rechnungskopf, je Kunde beliebig viele';
COMMENT ON COLUMN rechnungen.geaendert_am IS E'Letzte Aenderung via trg_rechnungen_aud gesetzt';
CREATE INDEX idx_rechnungen_kunde_datum ON rechnungen (kunden_id, rechnungsdatum desc);
CREATE INDEX idx_rechnungen_status ON rechnungen (status);
ALTER TABLE rechnungen ADD UNIQUE (rechnungsnummer);
ALTER TABLE rechnungen ADD PRIMARY KEY (id);
ALTER TABLE rechnungen ADD CONSTRAINT ck_rechnung_betrag CHECK (betrag_netto >= 0 AND betrag_brutto >= 0);
ALTER TABLE rechnungen ADD CONSTRAINT ck_rechnung_status CHECK (status IN ('OFFEN','BEZAHLT','STORNIERT','MAHNUNG'));
ALTER TABLE rechnungen ALTER COLUMN ID SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN RECHNUNGSNUMMER SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN KUNDEN_ID SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN RECHNUNGSDATUM SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN BETRAG_NETTO SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN MWST_SATZ SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN BETRAG_BRUTTO SET NOT NULL;
ALTER TABLE rechnungen ALTER COLUMN STATUS SET NOT NULL;


CREATE TABLE rechnungspositionen (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	rechnung_id bigint NOT NULL,
	position bigint NOT NULL,
	beschreibung varchar(200) NOT NULL,
	menge decimal(10,3) NOT NULL DEFAULT 1,
	einheit varchar(20) NOT NULL DEFAULT 'Stk',
	einzelpreis decimal(10,2) NOT NULL,
	gesamtpreis decimal(10,2) NOT NULL,
	position_summe decimal(12,2)
) ;
COMMENT ON TABLE rechnungspositionen IS E'Einzelne Positionen einer Rechnung';
COMMENT ON COLUMN rechnungspositionen.position_summe IS E'menge * einzelpreis, via trg_position_summe gesetzt';
CREATE INDEX ix_pos_rechnung ON rechnungspositionen (rechnung_id);
ALTER TABLE rechnungspositionen ADD UNIQUE (rechnung_id,position);
ALTER TABLE rechnungspositionen ADD PRIMARY KEY (id);
ALTER TABLE rechnungspositionen ADD CONSTRAINT ck_pos_menge CHECK (menge > 0);
ALTER TABLE rechnungspositionen ADD CONSTRAINT ck_pos_preis CHECK (einzelpreis >= 0 AND gesamtpreis >= 0);
ALTER TABLE rechnungspositionen ALTER COLUMN ID SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN RECHNUNG_ID SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN POSITION SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN BESCHREIBUNG SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN MENGE SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN EINHEIT SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN EINZELPREIS SET NOT NULL;
ALTER TABLE rechnungspositionen ALTER COLUMN GESAMTPREIS SET NOT NULL;
ALTER TABLE rechnungen ADD CONSTRAINT fk_rechnung_kunde FOREIGN KEY (kunden_id) REFERENCES kunden(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rechnungspositionen ADD CONSTRAINT fk_pos_rechnung FOREIGN KEY (rechnung_id) REFERENCES rechnungen(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
