-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

SET search_path = app_demo,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS trg_position_summe ON rechnungspositionen CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg_position_summe() RETURNS trigger AS $BODY$
BEGIN
    NEW.position_summe := NEW.menge * NEW.einzelpreis;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_trg_position_summe() FROM PUBLIC;

CREATE TRIGGER trg_position_summe
	BEFORE INSERT OR UPDATE ON rechnungspositionen FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_trg_position_summe();

DROP TRIGGER IF EXISTS trg_rechnungen_aud ON rechnungen CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg_rechnungen_aud() RETURNS trigger AS $BODY$
BEGIN
    NEW.geaendert_am := CURRENT_TIMESTAMP;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_trg_rechnungen_aud() FROM PUBLIC;

CREATE TRIGGER trg_rechnungen_aud
	BEFORE UPDATE ON rechnungen FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_trg_rechnungen_aud();

