-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

SET search_path = app_demo,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE OR REPLACE VIEW v_kunde_umsatz (kunden_id, kundenname, land, anzahl_rechnungen, umsatz_bezahlt, umsatz_offen) AS SELECT k.id                                   AS kunden_id,
       k.vorname || ' ' || k.name             AS kundenname,
       k.land,
       COUNT(r.id)                            AS anzahl_rechnungen,
       coalesce(SUM(CASE WHEN r.status = 'BEZAHLT'
                    THEN r.betrag_brutto END), 0) AS umsatz_bezahlt,
       coalesce(SUM(CASE WHEN r.status = 'OFFEN'
                    THEN r.betrag_brutto END), 0) AS umsatz_offen
  FROM kunden     k
  LEFT JOIN rechnungen r ON r.kunden_id = k.id
 GROUP BY k.id, k.vorname, k.name, k.land;

COMMENT ON VIEW v_kunde_umsatz  IS E'Aggregierte Umsaetze je Kunde, aufgeteilt nach Status';


